---
- name: Playbook setup de la normalisation
  hosts: all
  remote_user: ubuntu
  become: true

  tasks:
    - name: Install python3-pip
      ansible.builtin.apt:
        name: python3-pip
        update_cache: yes

    - name : Git clone app repo
      ansible.builtin.git:
        repo: https://github.com/ADataGuru-labs/webinar-python-borne-electrique.git
        dest: /home/ubuntu/webinar-python-borne-electrique

    - name : Install requirements
      ansible.builtin.pip:
        requirements: /home/ubuntu/webinar-python-borne-electrique/application/requirements.txt