name: Pipeline ci/cd


on:
  push:
    branches:
      - "feature/*"

env:
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Installer les dependances
        run: |
          pip install -r application/requirements.txt
          pip install -e .
      - name: Verifier la syntaxe du code
        run: |
          black --check .
      - name: Executer les tests
        run: |
          pytest application/normalisation/test

  package:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: myci-actions/add-deb-repo@10
        with:
          repo: deb [arch=amd64] https://apt.releases.hashicorp.com focal main
          keys-asc: https://apt.releases.hashicorp.com/gpg
          update: true
          install: packer
      - run: |
          packer build infrastructure/image/packer/setup_api.pkr.hcl


  deploy:
    runs-on: ubuntu-latest
    needs: package

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: |
          cd infrastructure/terraform && terraform init
      - run : |
          cd infrastrucutre/terraform && terraform apply -auto-approve

