name: Build When Merge on Master
run-name: BUILDING BRANCH ${{ github.ref }}


env:
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

on:
  push:
    branches:
      - 'main'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: myci-actions/add-deb-repo@10
        with:
          repo: deb [arch=amd64] https://apt.releases.hashicorp.com focal main
          keys-asc: https://apt.releases.hashicorp.com/gpg
          update: true
          install: packer
      - run: |
          packer build infrastructure/image/packer/setup_api.pkr.hcl


  deploy:
    runs-on: ubuntu-latest
    needs: package

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: |
           cd infrastructure/terraform/ec2 && terraform init
      - run: |
           cd infrastructure/terraform/ec2 && terraform apply -auto-approve
