name: Build When Merge on Master
run-name: BUILDING BRANCH ${{ github.ref }}


env:
  ENVIRONMENT: production
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: SET UP PYTHON ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: INSTALL DEPENDENCIES
        run: |
          if [ -f application/requirements.txt ]; then pip install -r application/requirements.txt; fi
          pip install -e .
      - name: CHECK SYNTAX
        run: |
          # stop the build if there are Python syntax errors
          black --check .
      - name: TEST
        run: |
          pytest application/normalisation/test

  package:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: LOGIN TO DOCKER HUB
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: DOCKER BUILD IMAGE
        run: |
          docker build . -t adataguru/webinar-python-borne-electrique:$ENVIRONMENT
          docker push adataguru/webinar-python-borne-electrique:$ENVIRONMENT
      - name: DOCKER PUSH IMAGE
        run: |
          docker push adataguru/webinar-python-borne-electrique:$ENVIRONMENT

  deploy:
    runs-on: ubuntu-latest
    needs: package

    steps:
      - uses: actions/checkout@v3
      - name: GET IMAGE FROM DOCKER HUB
        run: |
          docker pull adataguru/webinar-python-borne-electrique:$ENVIRONMENT
      - name: EXECUTE DOCKER CONTAINER TO SEND DATA
        run: |
          docker run --env AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --env AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --name send_data adataguru/webinar-python-borne-electrique:$ENVIRONMENT