name: Build When Merge on Master
run-name: BUILDING BRANCH ${{ github.ref }}


env:
  ENVIRONMENT: production
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  package:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: myci-actions/add-deb-repo@10
        with:
          repo: deb [arch=amd64] https://apt.releases.hashicorp.com focal main
          keys-asc: https://apt.releases.hashicorp.com/gpg
          update: true
          install: packer
      - run: |
          packer --version
          export PACKER_LOG=1
          packer build infrastructure/image/packer/setup_api.pkr.hcl
