name: Build when cron is triggered
run-name: PRODUCTION DEPLOY FROM BRANCH ${{ github.ref }}

env:
  ENVIRONMENT: production
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: GET IMAGE FROM DOCKER HUB
        run: |
          docker pull adataguru/webinar-python-borne-electrique:$ENVIRONMENT
      - name: EXECUTE DOCKER CONTAINER TO SEND DATA
        run: |
          docker run --name send_data adataguru/webinar-python-borne-electrique:$ENVIRONMENT